name: ci

on:
  push:
    branches: [ master ]
    paths:
    - 'docker/**'
    - '.github/**'

  pull_request:
    paths:
    - 'docker/**'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build skyhook image
      env:
        CEPH_VERSION: v15.2.4
      run: |
        docker build \
          -t jcnitdgp25/skyhookdm-arrow:latest \
          --build-arg CEPH_VERSION=$CEPH_VERSION \
          --file docker/Dockerfile \
          .
