name: ci

on:
  push:
    branches: [ master ]
    paths:
    - 'skyhookdm-image/**'
    - 'client-image/**'
    - '.github/**'

  pull_request:
    paths:
    - 'skyhookdm-image/**'
    - 'client-image/**'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: clone the repository
      run: |
        git clone \
          --branch rados-dataset-dev \
          --depth=1 \
          https://github.com/uccross/arrow

    - name: login to dockerhub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u jcnitdgp25 \
                     --password "$DOCKER_PASSWORD"

    - name: build skyhook image
      env:
        CEPH_VERSION: v15.2.4
      run: |
        docker build \
          -t jcnitdgp25/skyhookdm-arrow:latest \
          --build-arg CEPH_VERSION=$CEPH_VERSION \
          skyhookdm-image/
    
    - name: push skyhook latest version
      run: |
        docker push jcnitdgp25/skyhookdm-arrow:latest

    - name: push skyhook tagged version
      run: |
        NOW=$(date '+%F-%H-%M')
        docker tag jcnitdgp25/skyhookdm-arrow:latest \
                   jcnitdgp25/skyhookdm-arrow:$NOW

        docker push jcnitdgp25/skyhookdm-arrow:$NOW
    
    - name: build client image
      run: |
        docker build \
          -t jcnitdgp25/skyhookdm-client:latest \
          client-image/
    
    - name: push client latest version
      run: |
        docker push jcnitdgp25/skyhookdm-client:latest

    - name: push client tagged version
      run: |
        NOW=$(date '+%F-%H-%M')
        docker tag jcnitdgp25/skyhookdm-client:latest \
                   jcnitdgp25/skyhookdm-client:$NOW

        docker push jcnitdgp25/skyhookdm-client:$NOW
