name: skyhookdm

on:
  push:
    branches: [ master ]
    paths:
    - 'skyhookdm-image/**'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: login to dockerhub
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u jcnitdgp25 \
                     --password "$DOCKER_PASSWORD"

    - name: build image
      env:
        CEPH_VERSION: v15.2.4
      run: |
        docker build \
          -t jcnitdgp25/skyhookdm-arrow:latest \
          --build-arg CEPH_VERSION=$CEPH_VERSION \
          skyhookdm-image/
    
    - name: push latest version
      run: |
        docker push jcnitdgp25/skyhookdm-arrow:latest

    - name: push tagged version
      run: |
        NOW=$(date '+%F-%H-%M')
        docker tag jcnitdgp25/skyhookdm-arrow:latest \
                   jcnitdgp25/skyhookdm-arrow:$NOW

        docker push jcnitdgp25/skyhookdm-arrow:$NOW
